---
language: objective-c
before_install:
- sudo easy_install pip
- curl -L https://gist.githubusercontent.com/rricard/63ae797d7d1a33984318/raw/a833ba44e7be8428d877e58640720ff43c59dbad/uninstall_homebrew.sh | sudo /bin/sh
install:
- sudo pip install ansible
script:
- echo localhost > inventory
- ansible-playbook --syntax-check -i inventory test.yml
- ansible-playbook -i inventory test.yml --connection=local -s -vvvv -e installation_method=clone
- ansible-playbook -i inventory test.yml --connection=local -s -vvvv -e installation_method=script
